apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/neumanf/mally-api
          env:
            - name: FRONTEND_URL
              value: https://mally.neumanf.com
            - name: KEYCLOAK_ISSUER_URL
              value: https://auth.mally.neumanf.com/realms/mally
            - name: DATABASE_URL
              value: postgresql://postgres:5432/mally
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 3
