apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - name: ui
      protocol: TCP
      port: 80
      targetPort: 80
    - name: ui
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/neumanf/mally-ui
          readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 3