services:
    postgres:
        container_name: mally-postgres
        build:
            context: .
            dockerfile: ./infra/postgres/Dockerfile
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "postgres" ]
            timeout: 45s
            interval: 10s
            retries: 5
        environment:
            POSTGRES_DBS: 'mally,keycloak'
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - .env
        networks:
            - mally-network
        volumes:
            - postgres:/var/lib/postgresql/data

    keycloak:
        container_name: mally-keycloak
        build:
            context: .
            dockerfile: ./infra/keycloak/Dockerfile
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://0.0.0.0:9000/health/ready"]
            timeout: 45s
            interval: 10s
            retries: 15
        environment:
            JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres/keycloak
            KC_DB_USERNAME: ${POSTGRES_USER}
            KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
            KC_HEALTH_ENABLED: 'true'
            KC_HTTP_ENABLED: 'true'
            KC_METRICS_ENABLED: 'true'
            KC_HOSTNAME_STRICT_HTTPS: 'false'
            KC_HOSTNAME_URL: ${KEYCLOAK_URL}
            KC_PROXY: edge
            KC_PROXY_HEADERS: xforwarded
            KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
        env_file:
            - .env
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - mally-network
        command: start --hostname ${KEYCLOAK_URL} --import-realm

    api:
        container_name: mally-api
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/health/" ]
            timeout: 45s
            interval: 10s
            retries: 15
        environment:
            DATABASE_URL: ${POSTGRES_URL}
            DATABASE_USERNAME: ${POSTGRES_USER}
            DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
            KEYCLOAK_ISSUER_URL: ${KEYCLOAK_ISSUER_URL}
            FRONTEND_URL: ${FRONTEND_URL}
        env_file:
            -  .env
        volumes:
            - ./logs/api:/app/logs/api
        networks:
            - mally-network
        depends_on:
            postgres:
                condition: service_healthy
            keycloak:
                condition: service_healthy

    ui:
        container_name: mally-ui
        build:
            context: .
            dockerfile: ./apps/ui/Dockerfile
        restart: unless-stopped
        networks:
            - mally-network
        depends_on:
            api:
                condition: service_healthy
            keycloak:
                condition: service_healthy

    nginx:
        container_name: mally-nginx
        build:
            context: .
            dockerfile: ./infra/nginx/Dockerfile
        restart: unless-stopped
        networks:
            - mally-network
        depends_on:
            - api
            - ui
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw

    loki:
        container_name: mally-loki
        build:
            context: .
            dockerfile: ./infra/loki/Dockerfile
        restart: unless-stopped
        command: -config.file=/etc/loki/loki.yml
        networks:
            - mally-network

    promtail:
        container_name: mally-promtail
        build:
            context: .
            dockerfile: ./infra/promtail/Dockerfile
        restart: unless-stopped
        volumes:
            - ./logs/api/:/var/log/
        command: -config.file=/etc/promtail/promtail.yml
        networks:
            - mally-network

    prometheus:
        container_name: mally-prometheus
        build:
            context: .
            dockerfile: ./infra/prometheus/Dockerfile
        restart: unless-stopped
        command: '--config.file=/etc/prometheus/config.yml'
        networks:
            - mally-network

    grafana:
        container_name: mally-grafana
        build:
            context: .
            dockerfile: ./infra/grafana/Dockerfile
        restart: unless-stopped
        environment:
            GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
            GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
        env_file:
            - .env
        volumes:
            - grafana:/var/lib/grafana
        networks:
            - mally-network

volumes:
    postgres:
    grafana:

networks:
    mally-network:
        name: mally-network
