version: '3.3'

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: 'maly_db'
      POSTGRES_USER: 'maly'
      POSTGRES_PASSWORD: 'maly'
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data