spring:
    datasource:
        url: jdbc:${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driverClassName: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    main:
        allow-bean-definition-overriding: true

    cache:
        jcache:
          config: classpath:ehcache.xml

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_ISSUER_URL}

    rabbitmq:
      host: ${RABBITMQ_HOST:localhost}
      port: ${RABBITMQ_PORT:5672}
      username: ${RABBITMQ_USER:mally}
      password: ${RABBITMQ_PASSWORD:mally}

influx:
  url: ${INFLUX_URL:http://localhost:8086}
  username: ${INFLUX_USER:mally}
  password: ${INFLUX_PASSWORD:mally123}
  token: ${INFLUX_TOKEN:mally123}
  org: ${INFLUX_ORG:mally}
  buckets: url-clicks

logging:
  config: classpath:logback-prod.xml

management:
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"
  metrics:
    tags:
      application: 'Mally'

bucket4j:
    enabled: true
    filter-config-caching-enabled: true
    filter-config-cache-name: filterConfigCache
    filters:
        - id: url_shortener_redirect
          cache-name: buckets
          http-response-body: '{ "status": "error", "message": "Too many requests", "data": null, "errors": [] }'
          url: /url-shortener/redirect/.*
          http-response-headers:
            Access-Control-Allow-Origin: ${FRONTEND_URL}
          rate-limits:
              - cache-key: getRemoteAddr()
                bandwidths:
                    - capacity: 50
                      time: 1
                      unit: minutes
        - id: url_shortener_shorten
          cache-name: buckets
          http-response-body: '{ "status": "error", "message": "Too many requests", "data": null, "errors": [] }'
          url: /url-shortener/shorten
          http-response-headers:
            Access-Control-Allow-Origin: ${FRONTEND_URL}
          rate-limits:
              - cache-key: getRemoteAddr()
                bandwidths:
                    - capacity: 30
                      time: 1
                      unit: hours
        - id: pastebin_get_paste
          cache-name: buckets
          http-response-body: '{ "status": "error", "message": "Too many requests", "data": null, "errors": [] }'
          url: /pastebin/paste/.*
          http-response-headers:
            Access-Control-Allow-Origin: ${FRONTEND_URL}
          rate-limits:
              - cache-key: getRemoteAddr()
                bandwidths:
                    - capacity: 50
                      time: 1
                      unit: minutes
        - id: pastebin_paste
          cache-name: buckets
          http-response-body: '{ "status": "error", "message": "Too many requests", "data": null, "errors": [] }'
          url: /url-shortener/shorten
          http-response-headers:
            Access-Control-Allow-Origin: ${FRONTEND_URL}
          rate-limits:
              - cache-key: getRemoteAddr()
                bandwidths:
                    - capacity: 30
                      time: 1
                      unit: hours

mally:
    client:
        url: ${FRONTEND_URL}
