spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mally
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    main:
        allow-bean-definition-overriding: true

    cache:
        jcache:
            config: classpath:ehcache.xml

    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: "http://localhost:9090/realms/mally"

logging:
    config: classpath:logback-test.xml

bucket4j:
    enabled: true
    filter-config-caching-enabled: true
    filter-config-cache-name: filterConfigCache

mally:
    client:
        url: 'http://localhost:4200'
