server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-boot-app
    static_configs:
      - targets:
          - api:8080
        labels:
          job: spring-boot-app
          __path__: /var/log/*log
    pipeline_stages:
      - multiline:
          firstline: '^\[\w+]'
          max_wait_time: 3s
