name: CI

on:
    push:

jobs:
    format:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./apps/ui
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Install dependencies
              run: npm install --only=dev
            - name: Format frontend code
              run: npm run format
