name: CI

on:
    push:

jobs:
    format:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./apps/ui
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@4
            - name: Install dependencies
              run: npm install --only=dev
            - name: Format frontend code
              run: npm run format

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run backend
              uses: JarvusInnovations/background-action@v1
              with:
                run: docker compose -f docker-compose.testing.yml up &
                wait-on: http://localhost:8080/health/
                wait-for: 10m

            - name: Run Cypress
              uses: cypress-io/github-action@v3
              with:
                  working-directory: ./apps/ui
                  browser: chrome
                  build: curl http://localhost:8080/health/
                  start: npm start
                  wait-on: "http://localhost:4200"
